# Config for collecting a large amount of training data for the GNN

eco_path: "data/training/ecological/"
bio_path: "data/training/biological"
output_path: "data/training/state_action_pairs.jsonl"
master_seed: 42
time_limit: 60
search_depth_grid:
  - 500
  - 1000
  - 5000
gamma_range:
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
