# Config file containing GNN hyperparameters.

node_feat_dim: 5
graph_feat_dim: 5

hidden_dim: 128
num_gin_layers: 3       
mlp_layers_per_gin: 2   
final_mlp_layers: 2     
readout: mean          
dropout: 0.4
activation: LeakyReLU    
num_classes: 3
lr: 0.0005             
batch_size: 64
epochs: 50               
