# Config for collecting a large amount of training data for the GNN

eco_path: "data/training/ecological/"
bio_path: "data/training/biological/"
output_path: "data/training/state_action_pairs.jsonl"
master_seed: 42
time_limit: 60
synthetic_graphs: True
num_instances: 100
search_depth_grid:
  - 500
  - 1000
  - 5000
gamma_range:
  - 0.5
  - 0.55
  - 0.6
  - 0.65
  - 0.7
  - 0.75
  - 0.8
  - 0.85
  - 0.9
  - 0.95
